project:
  type: website

website:
  title: "miles a. moore"
  favicon: "assets/miles/favicon2.svg"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: news/index.qmd
        text: News
      - href: research/index.qmd
        text: Research
    tools:
      # - icon: github
      #   href: https://github.com/milesalanmoore
        # text: My Github Profile
        # target: "_blank"
  page-footer:  
    left: >-
     &#169; 2025 Miles Alan Moore &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="https://bsky.app/profile/milesalanmoore.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< fa brands bluesky >}}</a>
      <a class="link-dark me-1" href="https://linkedin.com/in/milesalanmoore" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://github.com/milesalanmoore" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0009-0003-0173-7602" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>

    right: 
      # - text: "Contact"
      #   aria-label: "Contact Form"
        # href: "contact.qmd"
      - text: "License"
        aria-label: "License Details"
        href: license.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light:
        - cosmo
        - assets/theme-light.scss
        - assets/miles/colors-light.scss
        # - assets/miles/fonts.scss
      dark: 
        - cosmo
        - assets/theme-dark.scss
        - assets/miles/colors-dark.scss
      
    css: styles.css
    toc: true

execute: 
  freeze: auto
