project:
  type: website

website:
  title: "miles a. moore"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: github
        href: https://github.com/milesalanmoore
        text: My Github Profile
        target: "_blank"
      - icon: linkedin
        href: https://www.linkedin.com/in/milesalanmoore
      # - icon: "{{< ai orcid >}}"
      #   href: https://orcid.org/0009-0003-0173-7602
  page-footer:  
    left: >-
     &#169; 2025 Miles Alan Moore &#8729; Made with [Quarto](https://quarto.org) in [VS Code](https://code.visualstudio.com/).
      
format:
  html:
    respect-user-color-scheme: false
    theme:
      light:
        - cosmo
        - assets/theme-light.scss
        - assets/miles/colors-light.scss
        # - assets/miles/fonts.scss
      dark: 
        - cosmo
        - assets/theme-dark.scss
        - assets/miles/colors-dark.scss
      
    css: styles.css
    toc: true

execute: 
  freeze: auto
