---
title: "Artificial Intelligence Use"
page-layout: full
toc-location: right
---

I believe in being transparent and explicit about the use of Generative 
Artificial Intelligence (AI) tools, like Large Language Models (LLMs), in my 
intellectual work. On this page, you'll find a collection of statements about if 
and how I use AI for specific tasks.

::: {.fs-3}
> Everything in my research and on this website was written by me.
:::

AI tools are becoming ubiquitous in the daily workflow of many knowledge workers. 
These text-generation models are showing up in email applications, coding 
environments, job application portals, internet search engines, and just about 
anywhere else they can be embedded. The implicit promise of these tools is that 
they save time and money by reducing the amount of human effort required in 
tasks ranging from mundane to mission-critical. Here's how I am using 
(or not using) these tools:

::: {.callout-note}
#### The /ai manifesto

I was inspired to write this page by [Andrew Heiss' own version](https://www.andrewheiss.com/ai/) of this sort of statement, as well as the references he linked: ["The '/ai' manifesto"](https://www.bydamo.la/p/ai-manifesto). See [the /ai public database](https://slashai.page/) for more.
:::


# Writing
I am **strongly** opposed to the use of AI for *writing* anything. I have been 
particularly persuaded by arguments in this area that, because LLMs are 
statistical prediction machines, the model is completely and utterly incapable 
of regard for the moral or ethical content of the text that it generates. It is 
also almost impossible to verify the intellectual provenance of any text 
generated. In short, there is not a human behind the writing, so how could it 
possibly be worth reading? For this reason, **I do not use LLMs to generate any 
portion of a research paper, cover letter, grant, email, blog post, 
course assignment, or similar text**. While this website was built with extensive 
(and agentic) help from Gen. A.I., all of the text on this website is my own 
writing.


# Coding
Generative A.I. tools are amazingly good at coding. Transformers and embeddings 
are really amazing technologies and the rigid syntactical structure of programming 
is a match made in heaven for them. I use Gen. AI to help me write code. 
Specifically, I use them to: 

::: {}
1. Document or comment on long scripts or functions.  
2. Turn a chunk of code I’ve written into a more general function with type checks and tests.  
3. Translate from one language to another.  
4. Explain complex code chunks.  
5. Review code for logical errors or potential problems.  
6. Plotting data
:::

Some important nuance is worth discussing here. As a scientist, it is extremely 
important to me that I have complete ownership over the most critical software 
and ideas upon which my scientific inference depends. That is: theory, simulations, 
statistical models, etc. The central code is and always will be code and logic 
that *I wrote.* Having said that, in addition to the uses above, I also use AI 
to help me write this critical code. However, I think adding friction to my 
workflow when developing the most important code is a good thing (i.e. Using the 
web-based chat interface to frontier intelligence models rather than agentic harnesses). 
This ensures I stay on top of what the code and math I am writing is actually doing. 
IF I do leverage agentic (Claude Code, OpenCode, etc.) tools to build models, I use 
seperate working directories and only simulated data. I sometimes use this 
more automated modality to prototype ideas. When I do, I like to use Agents that 
I built myself so that the output is very similar to how I write code and in this
way is much easier to audit and review en masse.

# Learning
I think this might be one of the worst use cases for LLMs, depending on *what* 
exactly is being "learned." I value the struggle in learning something new. I 
think that is what actually develops problem-solving and critical thinking. 
Nonetheless, I do find Gen A.I. to be occassionally very helpful in learning 
a new concept in math or programming. It isn't where I turn to first though. I 
am a huge fan of hardcopy textbooks, visualize demonstrations, lecture videos, 
and doing exercises to learn material.


# Images and Video
I have less sophisticated thoughts here currently. I have used Generative AI to 
create images before. In fact, the little favicon for this website was generated 
using an LLM! When I see AI generated figures in presentations though, something 
about it irritates me a bit. Maybe I shouldn't be so grumpy about it though... 
if the graphic communicates information effectively I guess it is fine. Don't 
get me started on A.I. video though... 
